### ISSUE TITLE
prismic.min.js 404 not found

### ISSUE THREAD

**Issue by darrenbarklie** [prismicio/nextjs-blog#22]
Encountered an issue where the address for the prismic.min.js file was generating a 404 locally and upon deployment.  This results in styles not loading for index and blog single pages.

```
localhost/:11 GET http://localhost:3000/%22https://static.cdn.prismic.io/prismic.min.js?repo=project&new=true%22 404 (Not Found)
```

This is resolved by changing **PrismicScript.js** to remove the double quote characters from the `src` attribute:

```
src={`https://static.cdn.prismic.io/prismic.min.js?repo=${repoName}&new=true`}
```

**Comment by a-trost** [comment]
This came back in a recent commit @samlfair. Let me know if you want me to do a pull request. It's the same line that you fixed before.

**Comment by timotius02** [comment]
Just noticed my issue was the same as this one. Seems like an quick fix is to reimplement the fix that was already merged.
