### ISSUE TITLE
Global styles are not loaded after vercel deployment

### ISSUE THREAD

**Issue by mochetts** [prismicio/nextjs-blog#24]
After deploying this app with vercel, global styles are not applied.

### In my local
![image](https://user-images.githubusercontent.com/3678598/102021968-80af6600-3d62-11eb-9ce3-3678172dc79d.png)

### In vercel
![image](https://user-images.githubusercontent.com/3678598/102021986-8f961880-3d62-11eb-95c0-7ec3df393413.png)

Here's the vercel app URL: https://mochetts-prismic-blog.vercel.app/

What I found so far is that [the global and reset styles](https://github.com/prismicio/nextjs-blog/blob/master/pages/_document.js#L19-L20) are not added to the header when running the `next build` command.

**Comment by mochetts** [comment]
**UPDATE:** I fixed it by moving the global & reset styles to the [DefaultLayout](https://github.com/prismicio/nextjs-blog/blob/master/layouts/index.js).

**Comment by samlfair** [comment]
@mochetts Thanks for pointing this out.

@levimykel It looks like global styles don't always work in `~/pages/_document.js`:

https://stackoverflow.com/questions/57205809/style-global-jsx-doesnt-seem-to-be-applied

Should we move the global styles to `~/layouts/index.js`, as @mochetts did?

**Comment by levimykel** [comment]
@samlfair It seems like the global styles need to be in `/pages/_app.js`.
https://nextjs.org/docs/basic-features/built-in-css-support#adding-a-global-stylesheet

**Comment by rialistic** [comment]
I can confirm this after banging my head on the wall for hours yesterday with the `nextjs-website` example.
There's an open issue about this also: https://github.com/vercel/next.js/issues/8522.

Anyway, it looks like this [has already been done]
(https://github.com/prismicio/nextjs-blog/commit/934284be93d2ab30f36c70e46acb1c5e0b471982), so I assume this can be closed?

**Comment by ristomatti** [comment]
I can confirm this after banging my head on the wall for hours yesterday with the `nextjs-website` example.
There's an open issue about this also: https://github.com/vercel/next.js/issues/8522.

Anyway, it looks like this [has already been done](https://github.com/prismicio/nextjs-blog/commit/934284be93d2ab30f36c70e46acb1c5e0b471982), so I assume this can be closed?
