### ISSUE TITLE
Error: An invalid API response was returned

### ISSUE THREAD

**Issue by cjlaserna** [prismicio/nextjs-blog#52]
I don't know why but anything I try on index.js (everything there regarding the client) breaks, await client.. does not work at all. I tried calling to the API myself and it worked fine, it only breaks in code. I didn't change anything from when I installed it.

**Comment by faresd** [comment]
This issue has been mentioned on **Prismic People**. There might be relevant details there:

https://community.prismic.io/t/example-code-does-not-work/10310/1

**Comment by angeloashmore** [comment]
Hi @cjlaserna, sorry for the delayed response. This issue should be fixed now by using the new `npx @slicemachine/init` command.

For reference, here is the full set of commands to clone and start a new project using this starter:

```sh
npx degit prismicio-community/nextjs-starter-prismic-blog your-project-name
cd your-project-name
npx @slicemachine/init
```

Thanks!
