### ISSUE TITLE
frontClient in prismicHelpers?

### ISSUE THREAD

**Issue by Jdruwe** [prismicio/nextjs-blog#9]
I am not sure what the following line does?

`  if (!req && frontClient) return frontClient;`

As frontClient is never assigned, am I missing something?

**Comment by levimykel** [comment]
Hi @Jdruwe, your timing is great, I was already planning on removing this as it is unnecessary. This has been fixed with [this commit](https://github.com/prismicio/nextjs-blog/commit/31104a34c78908b332dddbb1db114041c8719fc9) I just pushed.
